; Auto-generated. Do not edit!


(cl:in-package reap_unit_action-msg)


;//! \htmlinclude ControlReapResult.msg.html

(cl:defclass <ControlReapResult> (roslisp-msg-protocol:ros-message)
  ((total_dishes_cleaned
    :reader total_dishes_cleaned
    :initarg :total_dishes_cleaned
    :type cl:integer
    :initform 0))
)

(cl:defclass ControlReapResult (<ControlReapResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ControlReapResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ControlReapResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name reap_unit_action-msg:<ControlReapResult> is deprecated: use reap_unit_action-msg:ControlReapResult instead.")))

(cl:ensure-generic-function 'total_dishes_cleaned-val :lambda-list '(m))
(cl:defmethod total_dishes_cleaned-val ((m <ControlReapResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader reap_unit_action-msg:total_dishes_cleaned-val is deprecated.  Use reap_unit_action-msg:total_dishes_cleaned instead.")
  (total_dishes_cleaned m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ControlReapResult>) ostream)
  "Serializes a message object of type '<ControlReapResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'total_dishes_cleaned)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'total_dishes_cleaned)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'total_dishes_cleaned)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'total_dishes_cleaned)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ControlReapResult>) istream)
  "Deserializes a message object of type '<ControlReapResult>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'total_dishes_cleaned)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'total_dishes_cleaned)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'total_dishes_cleaned)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'total_dishes_cleaned)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ControlReapResult>)))
  "Returns string type for a message object of type '<ControlReapResult>"
  "reap_unit_action/ControlReapResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ControlReapResult)))
  "Returns string type for a message object of type 'ControlReapResult"
  "reap_unit_action/ControlReapResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ControlReapResult>)))
  "Returns md5sum for a message object of type '<ControlReapResult>"
  "58faa44dda59c6545bea63ff57491cbe")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ControlReapResult)))
  "Returns md5sum for a message object of type 'ControlReapResult"
  "58faa44dda59c6545bea63ff57491cbe")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ControlReapResult>)))
  "Returns full string definition for message of type '<ControlReapResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%uint32 total_dishes_cleaned~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ControlReapResult)))
  "Returns full string definition for message of type 'ControlReapResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%uint32 total_dishes_cleaned~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ControlReapResult>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ControlReapResult>))
  "Converts a ROS message object to a list"
  (cl:list 'ControlReapResult
    (cl:cons ':total_dishes_cleaned (total_dishes_cleaned msg))
))
