; Auto-generated. Do not edit!


(cl:in-package test_action-msg)


;//! \htmlinclude demoFeedback.msg.html

(cl:defclass <demoFeedback> (roslisp-msg-protocol:ros-message)
  ((complete_percent
    :reader complete_percent
    :initarg :complete_percent
    :type cl:float
    :initform 0.0))
)

(cl:defclass demoFeedback (<demoFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <demoFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'demoFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name test_action-msg:<demoFeedback> is deprecated: use test_action-msg:demoFeedback instead.")))

(cl:ensure-generic-function 'complete_percent-val :lambda-list '(m))
(cl:defmethod complete_percent-val ((m <demoFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader test_action-msg:complete_percent-val is deprecated.  Use test_action-msg:complete_percent instead.")
  (complete_percent m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <demoFeedback>) ostream)
  "Serializes a message object of type '<demoFeedback>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'complete_percent))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <demoFeedback>) istream)
  "Deserializes a message object of type '<demoFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'complete_percent) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<demoFeedback>)))
  "Returns string type for a message object of type '<demoFeedback>"
  "test_action/demoFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'demoFeedback)))
  "Returns string type for a message object of type 'demoFeedback"
  "test_action/demoFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<demoFeedback>)))
  "Returns md5sum for a message object of type '<demoFeedback>"
  "c375bca28786480387684f5bccabc0b5")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'demoFeedback)))
  "Returns md5sum for a message object of type 'demoFeedback"
  "c375bca28786480387684f5bccabc0b5")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<demoFeedback>)))
  "Returns full string definition for message of type '<demoFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback~%float32 complete_percent~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'demoFeedback)))
  "Returns full string definition for message of type 'demoFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback~%float32 complete_percent~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <demoFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <demoFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'demoFeedback
    (cl:cons ':complete_percent (complete_percent msg))
))
