; Auto-generated. Do not edit!


(cl:in-package test_action-msg)


;//! \htmlinclude demoResult.msg.html

(cl:defclass <demoResult> (roslisp-msg-protocol:ros-message)
  ((finish
    :reader finish
    :initarg :finish
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass demoResult (<demoResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <demoResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'demoResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name test_action-msg:<demoResult> is deprecated: use test_action-msg:demoResult instead.")))

(cl:ensure-generic-function 'finish-val :lambda-list '(m))
(cl:defmethod finish-val ((m <demoResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader test_action-msg:finish-val is deprecated.  Use test_action-msg:finish instead.")
  (finish m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <demoResult>) ostream)
  "Serializes a message object of type '<demoResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'finish) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <demoResult>) istream)
  "Deserializes a message object of type '<demoResult>"
    (cl:setf (cl:slot-value msg 'finish) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<demoResult>)))
  "Returns string type for a message object of type '<demoResult>"
  "test_action/demoResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'demoResult)))
  "Returns string type for a message object of type 'demoResult"
  "test_action/demoResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<demoResult>)))
  "Returns md5sum for a message object of type '<demoResult>"
  "474a58dbb494a45bb1ca99544cd64e45")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'demoResult)))
  "Returns md5sum for a message object of type 'demoResult"
  "474a58dbb494a45bb1ca99544cd64e45")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<demoResult>)))
  "Returns full string definition for message of type '<demoResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Definer the result~%bool finish~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'demoResult)))
  "Returns full string definition for message of type 'demoResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Definer the result~%bool finish~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <demoResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <demoResult>))
  "Converts a ROS message object to a list"
  (cl:list 'demoResult
    (cl:cons ':finish (finish msg))
))
