// Generated by gencpp from file reap_unit_action/ControlReapFeedback.msg
// DO NOT EDIT!


#ifndef REAP_UNIT_ACTION_MESSAGE_CONTROLREAPFEEDBACK_H
#define REAP_UNIT_ACTION_MESSAGE_CONTROLREAPFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace reap_unit_action
{
template <class ContainerAllocator>
struct ControlReapFeedback_
{
  typedef ControlReapFeedback_<ContainerAllocator> Type;

  ControlReapFeedback_()
    : percent_complete(0)  {
    }
  ControlReapFeedback_(const ContainerAllocator& _alloc)
    : percent_complete(0)  {
  (void)_alloc;
    }



   typedef uint32_t _percent_complete_type;
  _percent_complete_type percent_complete;





  typedef boost::shared_ptr< ::reap_unit_action::ControlReapFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::reap_unit_action::ControlReapFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct ControlReapFeedback_

typedef ::reap_unit_action::ControlReapFeedback_<std::allocator<void> > ControlReapFeedback;

typedef boost::shared_ptr< ::reap_unit_action::ControlReapFeedback > ControlReapFeedbackPtr;
typedef boost::shared_ptr< ::reap_unit_action::ControlReapFeedback const> ControlReapFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::reap_unit_action::ControlReapFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::reap_unit_action::ControlReapFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace reap_unit_action

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'reap_unit_action': ['/home/yangzt/yangzt_ws/devel/share/reap_unit_action/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::reap_unit_action::ControlReapFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::reap_unit_action::ControlReapFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::reap_unit_action::ControlReapFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::reap_unit_action::ControlReapFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::reap_unit_action::ControlReapFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::reap_unit_action::ControlReapFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::reap_unit_action::ControlReapFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c483d54fce63a45a8685bf35cceea187";
  }

  static const char* value(const ::reap_unit_action::ControlReapFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc483d54fce63a45aULL;
  static const uint64_t static_value2 = 0x8685bf35cceea187ULL;
};

template<class ContainerAllocator>
struct DataType< ::reap_unit_action::ControlReapFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "reap_unit_action/ControlReapFeedback";
  }

  static const char* value(const ::reap_unit_action::ControlReapFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::reap_unit_action::ControlReapFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Define a feedback message\n\
uint32 percent_complete\n\
\n\
";
  }

  static const char* value(const ::reap_unit_action::ControlReapFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::reap_unit_action::ControlReapFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.percent_complete);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ControlReapFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::reap_unit_action::ControlReapFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::reap_unit_action::ControlReapFeedback_<ContainerAllocator>& v)
  {
    s << indent << "percent_complete: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.percent_complete);
  }
};

} // namespace message_operations
} // namespace ros

#endif // REAP_UNIT_ACTION_MESSAGE_CONTROLREAPFEEDBACK_H
