// Generated by gencpp from file test_action/demoGoal.msg
// DO NOT EDIT!


#ifndef TEST_ACTION_MESSAGE_DEMOGOAL_H
#define TEST_ACTION_MESSAGE_DEMOGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace test_action
{
template <class ContainerAllocator>
struct demoGoal_
{
  typedef demoGoal_<ContainerAllocator> Type;

  demoGoal_()
    : numGoal(0)  {
    }
  demoGoal_(const ContainerAllocator& _alloc)
    : numGoal(0)  {
  (void)_alloc;
    }



   typedef uint32_t _numGoal_type;
  _numGoal_type numGoal;





  typedef boost::shared_ptr< ::test_action::demoGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::test_action::demoGoal_<ContainerAllocator> const> ConstPtr;

}; // struct demoGoal_

typedef ::test_action::demoGoal_<std::allocator<void> > demoGoal;

typedef boost::shared_ptr< ::test_action::demoGoal > demoGoalPtr;
typedef boost::shared_ptr< ::test_action::demoGoal const> demoGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::test_action::demoGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::test_action::demoGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace test_action

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'test_action': ['/home/yangzt/yangzt_ws/devel/share/test_action/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::test_action::demoGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test_action::demoGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test_action::demoGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test_action::demoGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_action::demoGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_action::demoGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::test_action::demoGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "32faa7c496e5a280a740c4602ed88a0f";
  }

  static const char* value(const ::test_action::demoGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x32faa7c496e5a280ULL;
  static const uint64_t static_value2 = 0xa740c4602ed88a0fULL;
};

template<class ContainerAllocator>
struct DataType< ::test_action::demoGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "test_action/demoGoal";
  }

  static const char* value(const ::test_action::demoGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::test_action::demoGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Define the goal\n\
uint32 numGoal\n\
";
  }

  static const char* value(const ::test_action::demoGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::test_action::demoGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.numGoal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct demoGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::test_action::demoGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::test_action::demoGoal_<ContainerAllocator>& v)
  {
    s << indent << "numGoal: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.numGoal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEST_ACTION_MESSAGE_DEMOGOAL_H
